### ISSUE TITLE
No Copyright notice

### ISSUE THREAD

**Issue by JonGaryOutlier** [Reklino/angular-resizable#82]
I know this is silly, but I'm using angular-resizable for my job, and the lawyers insist that I provide the copyright notice from each third-party component. This project doesn't have one that I've been able to find. If you would just toss something into the bottom of the Readme file, I would really appreciate it.

**Comment by Reklino** [comment]
Hm... This is new to me. Wouldn't a copyright notice give me **more** ownership and only make the legalities **more** complicated?

**Comment by JonGaryOutlier** [comment]
One would think lol. Red tape is so much fun.

**Comment by clebertsuconic** [comment]
@Reklino Can you consider adding the license please, if you don't want to provide a LICENSE your project is pretty much outside of the MIT license, and you should either hide the project as close source, or provide the LICENSE.

Or if you do care about copyright, use a more restrictive license... at least we would know what license is applied to this and people would just look for an alternative instead of using your project.

thank you

**Comment by Reklino** [comment]
Done! Sorry it took me so long to get around to this.
